title: "Elizabeth Crouther"
email: eacrouther@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  MLH Fellow and Master's student at the University of Pennsylvaina. I love tacos and chocolate, so mole sauce is the peak of existence
baseurl: "/"
url: "/elizabeths-portfolio"
twitter_username: 
github_username: eliboss
form_url: "https://formspree.io/f/mbjpbynw"

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
